Add validation for option label answer to be of type Radio,Checkbox and DropDown
ONSdigital/eq-questionnaire-validator pull request #134
Opened 2022-01-25 12:38 UTC by parimooa

### PR Context
Add validation for rules in option label from value to be of type Radio,Checkbox and Dropdown

### Checklist

* [ ] eq-translations updated to support any new schema keys which need translation

2022-01-25 16:46 UTC, MebinAbraham commented on app/validators/rules/rule_validator.py
> +        if not any(
Some spacing would help with readability, alternately this could just be `elif`.

2022-01-25 16:46 UTC, MebinAbraham commented on app/validators/rules/rule_validator.py
>          Validate the referenced answer id in `option-label-from-value` exists
Needs updating to reflect updated validation.

2022-01-25 19:03 UTC, MebinAbraham approved these changes

2022-01-25 20:01 UTC, LJBabbage requested changes

2022-01-25 20:01 UTC, LJBabbage commented on tests/validators/rules/test_rules_validator.py
> +def test_field_type_in_option_label_for_value_operator():
Could do with a tweak in the name, something like 
```
test_answer_type_invalid_for_option_label_from_value

2022-01-26 09:43 UTC, LJBabbage approved these changes

2022-01-26 09:45 UTC, merged